### ISSUE TITLE
After some full system update, i got "error while loading shared libraries: libalpm.so.13"

### ISSUE THREAD

**Issue by steven12138** [archlinux-downgrade/downgrade#224] opened 2024-03-14 00:50 UTC
### Checklist

- [x] No duplicate issues/PRs
- [x] Are you running the latest `downgrade` release from the [AUR](https://aur.archlinux.org/packages/downgrade/)?

### Environment

* System information: 

```
Linux stevenkerman 6.8.0-rc7-1-git-00260-gfa4b851b4ad6 #1 SMP PREEMPT_DYNAMIC Sun, 10 Mar 2024 20:34:52 +0000 x86_64 GNU/Linux
```
* Downgrade version:

```
╰─ downgrade --version     
11.3.0
```
### Questions/Help
```
╰─ sudo downgrade libalpm
pacsort: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
No results found
Unable to downgrade libalpm
```
After some full system update, i got "error while loading shared libraries: libalpm.so.13"
it's also affect `yay`, but i removed it and use `makepkg -si` to rebuilt yay and it fixed. but it didn't worked with `downgrade`

**Comment by pbrisbin** [comment] 2024-03-14 12:27
Are all of your packages up to date right now, or do you have some things already downgraded?

The error is indicating that `pacsort` depends on a specific versions of `libalpm`, which is not present. This mismatch is unlikely to be a situation that `downgrade` can help with, since it itself relies on a functional `pacsort`.

Knowing more about how you got into this situation could help us offer suggestions, but I doubt we'll find this to be a bug in `downgrade` itself, and it may just require some manual steps to resolve.

**Comment by steven12138** [comment] 2024-03-14 18:41
After upgrading all packages on my system using `yay` (I enable the `testing` source), it seems that the issue stems from the update of `libaplm`. Consequently, both `pacsort` and `downgrade` functionalities have been affected, rendering me unable to utilize `downgrade` to revert `libaplm` to its previous version and resolve the issue. At present, I am unsure how to address this problem.

i also checked `/var/cache/pacman/pkg/`, there is no previous version of `libaplm`

it's currently not a big deal, but i believe my system will be affect soon by some other fully system update.

**Comment by pbrisbin** [comment] 2024-03-14 18:50
Got it.

Yeah, so using `yay` and `testing` are both somewhat advanced and can certainly get you into a bind like this. I'm not sure the best way to get out of it, but you could try to [use the ALA manually](https://wiki.archlinux.org/title/Arch_Linux_Archive) to downgrade `libalpm`. Beyond that, you could go to the forums or IRC for support.

In any event, this seems unrelated to `downgrade` itself and is definitely not a bug, so I'll close the Issue.

**Closed by pbrisbin** 2024-03-14 18:50 UTC
Labels: question, triage

**Comment by steven12138** [comment] 2024-03-15 01:07
I've finally resolved the issue! Understanding that `libalpm` is a shared library within the `pacman` package, I reinstalled `pacman`, which automatically downgraded from version 6.1.0 to 6.0.2 (i really don;t know why). Afterwards, I reinstalled 'packagekit,' 'yay,' and 'downgrade.'

Thank you so much for your assistance! I truly appreciate it.

**Comment by steven12138** [comment] 2024-03-15 01:28
i know why. just caused by `testing`
